service: serverless-user-task-scheduler

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev
  # change this to use your own profile (https://serverless.com/framework/docs/providers/aws/guide/credentials#using-aws-profiles)
  profile: winterwind_serverless_deployer

functions:
  hello:
    handler: src/lambdas/hello.handle
  schedule-task:
    handler: src/lambdas/schedule-task.handle
    environment:
      statemachine_arn: ${self:resources.Outputs.TaskSchedulingStateMachine.Value}

stepFunctions:
  stateMachines:
    hellostepfunc1:
      name: TaskSchedulingStateMachine
      definition:
        Comment: "A Hello World example of the Amazon States Language using an AWS Lambda Function"
        StartAt: HelloWorld1
        States:
          HelloWorld1:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-hello"
            End: true

resources:
  Outputs:
    TaskSchedulingStateMachine:
      Description: The ARN of the TaskSchedulingStateMachine
      Value:
        Ref: TaskSchedulingStateMachine

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
